// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CarouselController from "./carousel_controller"
application.register("carousel", CarouselController)

import CartController from "./cart_controller"
application.register("cart", CartController)

import CheckoutController from "./checkout_controller"
application.register("checkout", CheckoutController)

import CounterController from "./counter_controller"
application.register("counter", CounterController)

import DownloadQrCodeController from "./download_qr_code_controller"
application.register("download-qr-code", DownloadQrCodeController)

import GetController from "./get_controller"
application.register("get", GetController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import ProductController from "./product_controller"
application.register("product", ProductController)

import RemoveProductController from "./remove_product_controller"
application.register("remove-product", RemoveProductController)

import ShoppingcartController from "./shoppingcart_controller"
application.register("shoppingcart", ShoppingcartController)

import ToggleController from "./toggle_controller"
application.register("toggle", ToggleController)
