// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CarouselController from "./carousel_controller"
application.register("carousel", CarouselController)

import CartController from "./cart_controller"
application.register("cart", CartController)

import CartcounterController from "./cartcounter_controller"
application.register("cartcounter", CartcounterController)

import CheckoutController from "./checkout_controller"
application.register("checkout", CheckoutController)

import ConfirmationController from "./confirmation_controller"
application.register("confirmation", ConfirmationController)

import CounterController from "./counter_controller"
application.register("counter", CounterController)

import DownloadQrCodeController from "./download_qr_code_controller"
application.register("download-qr-code", DownloadQrCodeController)

import FormSubmitController from "./form_submit_controller"
application.register("form-submit", FormSubmitController)

import GetController from "./get_controller"
application.register("get", GetController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import ProductController from "./product_controller"
application.register("product", ProductController)

import RemoveproductController from "./removeproduct_controller"
application.register("removeproduct", RemoveproductController)

import ShoppingcartController from "./shoppingcart_controller"
application.register("shoppingcart", ShoppingcartController)

import StarRatingController from "./star_rating_controller"
application.register("star-rating", StarRatingController)

import ToggleController from "./toggle_controller"
application.register("toggle", ToggleController)
