// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CarouselController from "./carousel_controller"
application.register("carousel", CarouselController)

import CounterController from "./counter_controller"
application.register("counter", CounterController)

import DownloadQrCodeController from "./download_qr_code_controller"
application.register("download-qr-code", DownloadQrCodeController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import ToggleController from "./toggle_controller"
application.register("toggle", ToggleController)
